parameters:
    darvin_rss.configuration.class: Darvin\RssBundle\Config\RssConfig

services:
    darvin_rss.configuration:
        class: '%darvin_rss.configuration.class%'
        arguments:
            - '%darvin_rss.entities%'
