parameters:
    darvin_rss.entity_router.class: Darvin\RssBundle\EntityRouter\EntityRouter

services:
    _defaults:
        public: true

    darvin_rss.entity_router:
        class: '%darvin_rss.entity_router.class%'
        public: false
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@router'
            - '@darvin_utils.homepage.router'
