parameters:
    darvin_rss.mapper.class: Darvin\RssBundle\Mapper\Mapper

services:
    darvin_rss.mapper:
        class: '%darvin_rss.mapper.class%'
        arguments:
            - '@property_accessor'
