parameters:
    darvin_rss.streamer.class: Darvin\RssBundle\Streamer\RssStreamer

services:
    darvin_rss.streamer:
        class: '%darvin_rss.streamer.class%'
        arguments:
            - '@darvin_rss.configuration'
            - '@doctrine.orm.entity_manager'
            - '@darvin_rss.rss_item_factory'
            - '@darvin_utils.locale.provider'
            - '@logger'
            - '@request_stack'
            - '@darvin_rss.rss_factory'
            - '@twig'
            - '%kernel.debug%'
